import { AxiosInterceptor } from '@/libs/config/axios'
import AuthProvider from '@/libs/context/AuthContext'
import { QueryClientProvider, ThemeProvider, ToastProvider } from '@/libs/provider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Construstor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ThemeProvider options={{ key: 'mui' }}>
          <ToastProvider>
            <AuthProvider>
              <AxiosInterceptor>
                <QueryClientProvider>{children}</QueryClientProvider>
              </AxiosInterceptor>
            </AuthProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
